spring.datasource.url=jdbc:postgresql://localhost:5433/journaling_db
spring.datasource.username=gruapim_user
spring.datasource.password=gruapim_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true